#!/usr/bin/python2

import  socket 
s=socket.socket(socket.AF_INET,socket.SOCK_DGRAM)


	
message=raw_input("navratan")
s.sendto(message,("192.168.10.68",9333))
while 5:
	message=raw_input("navratan")
	n = s.recvfrom(5000)
	print n[0]
	s.sendto(message,("192.168.10.68",n[1][1]))
	
	#s.bind((n[1][0],n[1][1]))

